#! /bin/bash
#
# Usage:
#  build
#
# This script builds the CentOS 6 and 7 ansible-support images.
#


main()
{
  local baseDir=$(dirname $(readlink -f "$0"))

  docker build --file "$baseDir"/Dockerfile.centos6 --tag ansible-support:centos6 "$baseDir"
  docker build --file "$baseDir"/Dockerfile.centos7 --tag ansible-support:centos7 "$baseDir"
}


set -e

main
