FROM centos:7
MAINTAINER Tony Edgin @ CyVerse

COPY config.sh /tmp

RUN /tmp/config.sh 7 && \
    ssh-keygen -q -f /etc/ssh/ssh_host_ecdsa_key -N '' -t ecdsa && \
    ssh-keygen -q -f /etc/ssh/ssh_host_ed25519_key -N '' -t ed25519 && \
    rm --force /tmp/config.sh

COPY entrypoint /

ENTRYPOINT [ "/entrypoint" ]
