FROM centos:7
MAINTAINER Tony Edgin @ CyVerse

# This image is based on the lemonbar/centos6-ssh image, but it allows unauthenticated logins by
# root.

COPY config.sh /tmp

# Configure for ansible
RUN rpm --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 && \
    /tmp/config.sh && \
    rpm --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 && \
    ssh-keygen -q -f /etc/ssh/ssh_host_ecdsa_key -N '' -t ecdsa && \
    ssh-keygen -q -f /etc/ssh/ssh_host_ed25519_key -N '' -t ed25519 && \
    rm --force /tmp/config.sh

COPY entrypoint /

ENTRYPOINT [ "/entrypoint" ]
