FROM centos:6
MAINTAINER Tony Edgin @ CyVerse

# This image is based on the lemonbar/centos6-ssh image, but it allows unauthenticated logins by
# root.

COPY config.sh /tmp

# Configure for ansible
RUN rpm --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6 && \
    /tmp/config.sh && \
    rpm --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6 && \
    rm --force /tmp/config.sh

COPY entrypoint /

ENTRYPOINT [ "/entrypoint" ]
