---
- name: Reboot | schedule
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      sleep 1
      reboot
  async: 1000000000
  poll: 0
  failed_when: false
  changed_when: true
  tags: no_testing

- name: Reboot | wait for server to come back up
  ansible.builtin.wait_for_connection:
    delay: 60
  tags: no_testing
