---
- name: configure | ensure enough vm huge pages
  ansible.posix.sysctl:
    name: vm.nr_hugepages
    value: "{{ pg_num_huge_pages }}"
    state: present
    sysctl_set: true
  notify:
    - reboot
  tags:
    - no_testing

- name: configure | ensure vm.swappiness is 5
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '5'
    state: present
    sysctl_set: true
  tags:
    - no_testing

- name: configure | ensure postgres user owns home dir
  file:
    path: /var/lib/postgresql
    state: directory
    owner: postgres
    group: postgres
    recurse: true

- name: configure | ensure archive dir exists
  file:
    state: directory
    path: "{{ pg_db_path }}/archive"
    owner: postgres
    group: postgres
    mode: "0770"

- name: configure | template configs
  template:
    src: cyverse.conf.j2
    dest: "{{ pg_conf_path }}/conf.d/cyverse.conf"
    owner: postgres
    group: postgres
    mode: "0640"
  notify:
    - restart postgres

- name: configure | ensure block in pg_hba.conf exists
  blockinfile:
    path: "{{ pg_conf_path }}/pg_hba.conf"
    insertafter: "{{ pg_hba_insertafter }}"
    marker: "# {mark} postgres12 MANAGED BLOCK2"
    block: |
      {% for entry in pg_hba_users %}
      {{ entry }}
      {% endfor %}
      {% if pg_upstream_node %}
      {%   set ip =
             pg_upstream_node if pg_upstream_node|ansible.utils.ipaddr else
             lookup('dig', pg_upstream_node) %}
      {{ '%-7s %-15s %-15s %-23s %s'
         | format(
           'host', 'replication', pg_replication_user, ip ~ '/32', 'trust' ) }}
      {% endif %}
      {% for replica in pg_downstream_nodes %}
      {%   set ip =
             replica if replica|ansible.utils.ipaddr else
             lookup('dig', replica) %}
      {{ '%-7s %-15s %-15s %-23s %s'
         | format(
           'host', 'replication', pg_replication_user, ip ~ '/32', 'trust' ) }}
      {% endfor %}
  notify:
    - restart postgres

- name: configure | template pgpass file
  template:
    src: pgpass.j2
    dest: /var/lib/postgresql/.pgpass
    owner: postgres
    group: postgres
    mode: "0600"
  when: pg_upstream_node or pg_downstream_nodes|length > 0
