---
- name: Enable untestable notifications
  ansible.builtin.set_fact:
    _notifications_enabled: true
  tags: no_testing

- name: Verify variables
  ansible.builtin.include_tasks: variables.yml

- name: Install
  ansible.builtin.include_tasks: install.yml

- name: Configure
  ansible.builtin.include_tasks: configure.yml

- name: Ensure postgresql is running
  ansible.builtin.meta: flush_handlers

- name: Set up replication
  ansible.builtin.include_tasks: replication.yml
