---
- name: Replication | create replication user
  community.postgresql.postgresql_user:
    db: "{{ postgres12_db }}"
    port: "{{ postgres12_listen_port }}"
    name: "{{ postgres12_replication_user }}"
    role_attr_flags: replication
    password: '{{ postgres12_replication_pass }}'
  when: postgres12_downstream_nodes|length > 0
  become: true
  become_user: postgres
  tags: no_testing

- name: Replication | start
  when: postgres12_upstream_node and postgres12_destroy_default_db_on_init
  block:
    - name: Stop database on secondaries
      ansible.builtin.service:
        name: postgresql@12-main.service
        state: stopped
      tags: no_testing

    - name: Ensure pgdata path is empty
      ansible.builtin.file:
        state: absent
        path: "{{ postgres12_db_path }}"
      register: delete_data_response

    - name: Replicate db from primary to secondaries
      when: delete_data_response is changed
      become: true
      become_user: postgres
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          pg_basebackup --progress --write-recovery-conf --no-password \
            --host={{ postgres12_upstream_node }} \
            --user={{ postgres12_replication_user }} \
            --port={{ postgres12_listen_port }} \
            --pgdata={{ postgres12_db_path }} \
            --format=plain \
            --wal-method=stream
      changed_when: true
      tags: skip_ansible_lint

    - name: Create standby.signal files on secondary postgres nodes
      ansible.builtin.copy:
        content: ""
        dest: "{{ postgres12_db_path }}/standby.signal"
        force: false
        group: postgres
        owner: postgres
        mode: 0600

    - name: Start database on secondaries
      ansible.builtin.service:
        name: postgresql@12-main.service
        state: started
      tags: no_testing
