#!/bin/bash

set -e

if [[ "$OSTYPE" == "darwin"* ]]
then
  readonly ExecName=$(greadlink -f "$0")
else
  readonly ExecName=$(readlink --canonicalize "$0")
fi

readonly PlaybooksDir=$(dirname "$ExecName")


main()
{
  local roleDir

  while read -r roleDir
  do
    local reqFile="$roleDir"/requirements.yml

    if [[ -f "$reqFile" ]]
    then
      # ansible-galaxy won't update roles installed through dependencies, so
      # delete all roles before updating
      local roles
      roles=$(listSubDirs "$roleDir" | sort)

      local keepers
      keepers=$(sed -n 's/^!\([^\/]*\)\/.*/\1/p' "$roleDir"/.gitignore | sort --unique)

      local role
      for role in $(comm -2 -3 <(echo "$roles") <(echo "$keepers"))
      do
        rm -f -r "${roleDir:?}"/"$role"
      done

      ansible-galaxy install --force --role-file="$reqFile" --roles-path="$roleDir"
    fi
  done < <(find "$PlaybooksDir" -type d -name roles)
}

listSubDirs()
{
  local roleDir="$1"

  if [[ "$OSTYPE" == "darwin"* ]]
  then
    find "$roleDir" -maxdepth 1 -mindepth 1 -type d -print0 | xargs -0 stat -f '%f\n'
  else
    find "$roleDir" -maxdepth 1 -mindepth 1 -type d -printf '%f\n'
  fi
}


main
