---
- include: install_ansible_support.yml

- include: block_access.yml

- include: open_control_port.yml

- include: upgrade_system_packages.yml
  when: manage_system

- include: upgrade_irods.yml

- include: restore_cyverse_access.yml

- include: reboot.yml
  when: manage_system

- name: wait for verification of install
  hosts: localhost
  tasks:
    - name: waiting for verification of install
      pause:
        prompt: Please make sure that iRODS still works.

- include: restore_access.yml
