---
- name: Prepare for PostgreSQL
  hosts: dbms
  become: true
  roles:
    - role: adfinis_sygroup.grub
      vars:
        grub_console: false
        grub_consoles: []
        grub_serial: []
        grub_timeout: 0
        grub_disable_network_predictable_interface_names: false
        grub_cmdline_linux_default_list:
          - transparent_hugepage=never
      tags: no_testing


- name: Set up primary DBMS
  hosts: dbms_primary
  become: true
  gather_facts: false
  vars:
    effective_cache_size: >-
      {{ _dbms_effective_cache_size if _dbms_effective_cache_size else
        (ansible_facts['memtotal_mb']|int // (2 * 1024)) }}GB
    max_worker_processes: >-
      {{ _dbms_max_worker_processes if _dbms_max_worker_processes else
        ansible_facts['processor_nproc'] }}
  roles:
    - role: postgres12
      vars:
        postgres12_checkpoint_completion_target: "{{ _dbms_checkpoint_completion_target }}"
        postgres12_checkpoint_timeout: "{{ _dbms_checkpoint_timeout }}min"
        postgres12_effective_cache_size: "{{ effective_cache_size }}"
        postgres12_extra_listen_addresses: "{{ ansible_facts['all_ipv4_addresses'] }}"
        postgres12_listen_port: "{{ _dbms_port }}"
        postgres12_log_line_prefix: "{{ _dbms_log_line_prefix }}"
        postgres12_log_min_duration_statement: "{{ _dbms_log_min_duration }}"
        postgres12_maintenance_work_mem: "{{ _dbms_maintenance_work_mem }}GB"
        postgres12_max_connections: "{{ _dbms_max_connections }}"
        postgres12_max_wal_size: "{{ _dbms_max_wal_size }}GB"
        postgres12_min_wal_size: "{{ _dbms_min_wal_size }}GB"
        postgres12_random_page_cost: "{{ _dbms_random_page_cost }}"
        postgres12_replication_pass: "{{ _dbms_replication_password }}"
        postgres12_replication_user: "{{ _dbms_replication_user }}"
        postgres12_shared_buffers: "{{ ansible_facts['memtotal_mb']|int // 4 }}MB"
        postgres12_standard_conforming_strings: 'off'
        postgres12_work_mem: "{{ _dbms_work_mem }}MB"
        postgres12_effective_io_concurrency: "{{ _dbms_effective_io_concurrency }}"
        postgres12_max_worker_processes: "{{ max_worker_processes }}"
        postgres12_max_parallel_workers: "{{ max_worker_processes }}"
        postgres12_max_parallel_workers_per_gather: "{{ _dbms_max_parallel_workers_per_gather }}"
        postgres12_max_parallel_maintenance_workers: "{{ _dbms_max_parallel_maintenance_workers }}"
        postgres12_wal_buffers: 16MB
        postgres12_num_huge_pages: "{{ _dbms_mem_num_huge_pages }}"
        postgres12_huge_pages: "{{ 'on' if _dbms_mem_num_huge_pages|int > 0 else 'off' }}"
        postgres12_downstream_nodes: "{{ groups['dbms_replicas'] }}"
        postgres12_wal_keep_segments: "{{ _dbms_wal_keep_segments }}"
        postgres12_restart_allowed: "{{ _dbms_restart_allowed }}"


- name: Set up replica DBMSs
  hosts: dbms_replicas
  become: true
  gather_facts: false
  vars:
    effective_cache_size: >-
      {{ _dbms_effective_cache_size if _dbms_effective_cache_size else
        (ansible_facts['memtotal_mb']|int // (2 * 1024)) }}GB
    max_worker_processes: >-
      {{ _dbms_max_worker_processes if _dbms_max_worker_processes else
        ansible_facts['processor_nproc'] }}
  roles:
    - role: postgres12
      vars:
        postgres12_checkpoint_completion_target: >-
          {{ _dbms_checkpoint_completion_target }}
        postgres12_checkpoint_timeout: "{{ _dbms_checkpoint_timeout }}min"
        postgres12_destroy_default_db_on_init: "{{ _dbms_replication_start }}"
        postgres12_effective_cache_size: "{{ effective_cache_size }}"
        postgres12_extra_listen_addresses: "{{ ansible_facts['all_ipv4_addresses'] }}"
        postgres12_listen_port: "{{ _dbms_port }}"
        postgres12_log_line_prefix: "{{ _dbms_log_line_prefix }}"
        postgres12_log_min_duration_statement: "{{ _dbms_log_min_duration }}"
        postgres12_maintenance_work_mem: "{{ _dbms_maintenance_work_mem }}GB"
        postgres12_max_connections: "{{ _dbms_max_connections }}"
        postgres12_max_wal_size: "{{ _dbms_max_wal_size }}GB"
        postgres12_min_wal_size: "{{ _dbms_min_wal_size }}GB"
        postgres12_random_page_cost: "{{ _dbms_random_page_cost }}"
        postgres12_replication_pass: "{{ _dbms_replication_password }}"
        postgres12_replication_user: "{{ _dbms_replication_user }}"
        postgres12_shared_buffers: "{{ ansible_facts['memtotal_mb']|int // 4 }}MB"
        postgres12_standard_conforming_strings: 'off'
        postgres12_work_mem: "{{ _dbms_work_mem }}MB"
        postgres12_effective_io_concurrency: "{{ _dbms_effective_io_concurrency }}"
        postgres12_max_worker_processes: "{{ max_worker_processes }}"
        postgres12_max_parallel_workers: "{{ max_worker_processes }}"
        postgres12_max_parallel_workers_per_gather: >-
          {{ _dbms_max_parallel_workers_per_gather }}
        postgres12_max_parallel_maintenance_workers: >-
          {{ _dbms_max_parallel_maintenance_workers }}
        postgres12_wal_buffers: 16MB
        postgres12_num_huge_pages: "{{ _dbms_mem_num_huge_pages }}"
        postgres12_huge_pages: >-
          {{ 'on' if _dbms_mem_num_huge_pages|int > 0 else 'off' }}
        postgres12_upstream_node: "{{ groups['dbms_primary'][0] }}"
        postgres12_start_allowed: "{{ _dbms_restart_allowed }}"
