---
- name: Prepare for PostgreSQL
  hosts: dbms
  become: true
  roles:
    - role: adfinis_sygroup.grub
      grub_console: false
      grub_consoles: []
      grub_serial: []
      grub_timeout: 0
      grub_disable_network_predictable_interface_names: false
      grub_cmdline_linux_default_list:
        - transparent_hugepage=never
      tags:
        - no_testing


- name: Set up primary DBMS
  hosts: dbms_primary
  become: true
  gather_facts: false
  vars:
    effective_cache_size: >-
      {{ _dbms_effective_cache_size if _dbms_effective_cache_size else
        (ansible_facts['memtotal_mb']|int // (2 * 1024)) }}GB
    max_worker_processes: >-
      {{ _dbms_max_worker_processes if _dbms_max_worker_processes else
        ansible_facts['processor_nproc'] }}
  roles:
    - role: postgres12
      vars:
        pg_checkpoint_completion_target: >-
          {{ _dbms_checkpoint_completion_target }}
        pg_checkpoint_timeout: "{{ _dbms_checkpoint_timeout }}min"
        pg_effective_cache_size: "{{ effective_cache_size }}"
        pg_extra_listen_addresses: "{{ ansible_facts['all_ipv4_addresses'] }}"
        pg_listen_port: "{{ _dbms_port }}"
        pg_log_line_prefix: "{{ _dbms_log_line_prefix }}"
        pg_log_min_duration_statement: "{{ _dbms_log_min_duration }}"
        pg_maintenance_work_mem: "{{ _dbms_maintenance_work_mem }}GB"
        pg_max_connections: "{{ _dbms_max_connections }}"
        pg_max_wal_size: "{{ _dbms_max_wal_size }}GB"
        pg_min_wal_size: "{{ _dbms_min_wal_size }}GB"
        pg_random_page_cost: "{{ _dbms_random_page_cost }}"
        pg_replication_pass: "{{ _dbms_replication_password }}"
        pg_replication_user: "{{ _dbms_replication_user }}"
        pg_shared_buffers: "{{ ansible_facts['memtotal_mb']|int // 4 }}MB"
        pg_standard_conforming_strings: 'off'
        pg_work_mem: "{{ _dbms_work_mem }}MB"
        pg_effective_io_concurrency: "{{ _dbms_effective_io_concurrency }}"
        pg_max_worker_processes: "{{ max_worker_processes }}"
        pg_max_parallel_workers: "{{ max_worker_processes }}"
        pg_max_parallel_workers_per_gather: >-
          {{ _dbms_max_parallel_workers_per_gather }}
        pg_max_parallel_maintenance_workers: >-
          {{ _dbms_max_parallel_maintenance_workers }}
        pg_wal_buffers: 16MB
        pg_num_huge_pages: "{{ _dbms_mem_num_huge_pages }}"
        pg_huge_pages: >-
          {{ 'on' if _dbms_mem_num_huge_pages|int > 0 else 'off' }}
        pg_downstream_nodes: "{{ groups['dbms_replicas'] }}"
        pg_wal_keep_segments: "{{ _dbms_wal_keep_segments }}"
        pg_reboot_allowed: "{{ _dbms_reboot_allowed }}"


- name: Set up replica DBMSs
  hosts: dbms_replicas
  become: true
  gather_facts: false
  vars:
    effective_cache_size: >-
      {{ _dbms_effective_cache_size if _dbms_effective_cache_size else
        (ansible_facts['memtotal_mb']|int // (2 * 1024)) }}GB
    max_worker_processes: >-
      {{ _dbms_max_worker_processes if _dbms_max_worker_processes else
        ansible_facts['processor_nproc'] }}
  roles:
    - role: postgres12
      vars:
        pg_checkpoint_completion_target: >-
          {{ _dbms_checkpoint_completion_target }}
        pg_checkpoint_timeout: "{{ _dbms_checkpoint_timeout }}min"
        pg_destroy_default_db_on_init: "{{ _dbms_replication_start }}"
        pg_effective_cache_size: "{{ effective_cache_size }}"
        pg_extra_listen_addresses: "{{ ansible_facts['all_ipv4_addresses'] }}"
        pg_listen_port: "{{ _dbms_port }}"
        pg_log_line_prefix: "{{ _dbms_log_line_prefix }}"
        pg_log_min_duration_statement: "{{ _dbms_log_min_duration }}"
        pg_maintenance_work_mem: "{{ _dbms_maintenance_work_mem }}GB"
        pg_max_connections: "{{ _dbms_max_connections }}"
        pg_max_wal_size: "{{ _dbms_max_wal_size }}GB"
        pg_min_wal_size: "{{ _dbms_min_wal_size }}GB"
        pg_random_page_cost: "{{ _dbms_random_page_cost }}"
        pg_replication_pass: "{{ _dbms_replication_password }}"
        pg_replication_user: "{{ _dbms_replication_user }}"
        pg_shared_buffers: "{{ ansible_facts['memtotal_mb']|int // 4 }}MB"
        pg_standard_conforming_strings: 'off'
        pg_work_mem: "{{ _dbms_work_mem }}MB"
        pg_effective_io_concurrency: "{{ _dbms_effective_io_concurrency }}"
        pg_max_worker_processes: "{{ max_worker_processes }}"
        pg_max_parallel_workers: "{{ max_worker_processes }}"
        pg_max_parallel_workers_per_gather: >-
          {{ _dbms_max_parallel_workers_per_gather }}
        pg_max_parallel_maintenance_workers: >-
          {{ _dbms_max_parallel_maintenance_workers }}
        pg_wal_buffers: 16MB
        pg_num_huge_pages: "{{ _dbms_mem_num_huge_pages }}"
        pg_huge_pages: >-
          {{ 'on' if _dbms_mem_num_huge_pages|int > 0 else 'off' }}
        pg_upstream_node: "{{ groups['dbms_primary'][0] }}"
        pg_reboot_allowed: "{{ _dbms_reboot_allowed }}"
