#! /bin/bash
#
# This script builds the Docker images that compose the testing environment and
# the ansible-tester image.


main()
{
  local baseDir=$(dirname $(readlink -f "$0"))

  "$baseDir"/env/build "$baseDir"/config.inc
  "$baseDir"/ansible-tester/build
}


set -e

main
