#!/usr/bin/env bash
#
# This script builds the Docker images that compose the testing environment and
# the ansible-tester image.

set -o errexit -o nounset -o pipefail

BASE_DIR="$(dirname "$(realpath --canonicalize-existing "$0")")"
readonly BASE_DIR

main() {
	"$BASE_DIR"/env/build "$BASE_DIR"/config.inc
	"$BASE_DIR"/ansible-tester/build "$BASE_DIR"/config.inc
}

main "$@"
