#! /bin/bash
#
# This script removes the images built by the build script. Specifically, it
# deletes ansible-tester, all of the images composing env, and the base image
# ansible-support.


main()
{
  local baseDir=$(dirname $(readlink -f "$0"))

  "$baseDir"/ansible-tester/clean
  "$baseDir"/env/clean "$baseDir"/config.inc
  "$baseDir"/ansible-support/clean
}


main
