#! /bin/bash
#
# This script removes the images built by the build script. Specifically, it
# deletes ansible-tester, all of the images composing env, and the base image
# ansible-support.


if [[ "$OSTYPE" == "darwin"* ]]
then
  readonly ExecName=$(greadlink -f "$0")
else
  readonly ExecName=$(readlink --canonicalize "$0")
fi

main()
{
  local baseDir=$(dirname "$ExecName")

  "$baseDir"/ansible-tester/clean
  "$baseDir"/env/clean "$baseDir"/config.inc
}


main
