#! /bin/bash
#
# Usage:
#  run PLAYBOOK_FOLDER [PLAYBOOK_NAME]
#
# Parameters:
#  PLAYBOOK_FOLDER  the absolute path to the directory holding the playbook
#  PLAYBOOK_NAME    the path to the playbook to test relative to PLAYBOOK_FOLDER
#
# This script runs a playbook with in the testing environment. If no playbook
# is provided, it will attempt to run the playbook PLAYBOOK_FOLDER/main.yml


main()
{
  local baseDir=$(dirname $(readlink -f "$0"))

  if [ "$#" -lt 1 ]
  then
    printf 'The name of a folder holding the playbook is requred\n' >&2
    return 1
  fi

  local playbooks="$1"

  if [ "$#" -ge 2 ]
  then
    local playbook="$2"
  else
    local playbook=main.yml
  fi

  local cfg="$baseDir"/config.inc

  . "$cfg"

  if ! [[ "$playbooks" =~ ^/ ]]
  then
    playbooks="$(pwd)"/"$playbooks"
  fi

  if ! [ -d "$playbooks" ]
  then
    printf '%s is not a directory\n' "$playbooks" >&2
    return 1
  fi

  if ! [ -f "$playbooks"/"$playbook" ]
  then
    printf 'The playbook %s/%s does not exist\n' "$playbooks" "$playbook" >&2
    return 1
  fi

  if "$baseDir"/env/controller "$cfg" start
  then
    docker run --interactive --rm --tty \
               --network "$ENV_NAME"_default --volume "$playbooks":/playbooks-under-test:ro \
               ansible-tester "$playbook"
  fi

  "$baseDir"/env/controller "$cfg" stop
}


main "$@"
