#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Usage:
    test_module <module_folder> <module_name>

Positional Arguments:
    <module_folder>  The folder the module is in
    <module_name>    The name of the module file

Optional Arguments:
    -I, --inventory-hosts <hosts>   the name of the inventory hosts file to use
    -h, --help                      show help and exit
    -i, --inspect                   after running the playbook, open shell that
                                    allows manual inspection of the
                                    configuration files, vaults, and logs
    -p, --pretty                    more information will be output and
                                    newlines will be expanded in that output.
    -v, --verbose                   lots of information will be written to
                                    output.
Example:
    ./test_module --inspect ../irods/library irods_group
"""

import os
import sys
from subprocess import Popen
import argparse

DEFAULT_HOSTS = "hosts-all"
BASEDIR = os.path.dirname(sys.argv[0])
CFG = BASEDIR + "/config.inc"


def main():
    """
    Entrypoint
    """
    args = parse_args()

    module_dir = os.path.abspath(args.module_folder)
    module_name = args.module_name
    playbook = os.path.join("test_" + args.module_name + ".yml")

    if not dir_exist(module_dir):
        print(f"{module_dir} not a directory")
        return
    if not module_exist(module_dir, module_name) and not module_exist(module_dir, f"{module_name}.py"):
        print(f"module {args.module_name} not found")
        return
    if not playbook_exist(module_dir, playbook):
        print(f"{playbook} not a file")
        return

    if controller("start") == 0:
        run_tester(args.inspect, args.pretty, module_dir, playbook, args.hosts, args.verbose)
    controller("stop")


def parse_args():
    """
    Parsing the command line argument
    """
    parser = argparse.ArgumentParser()

    parser.add_argument("module_folder",
                        help="the path to the root directory for a collection \
                        of module")

    parser.add_argument("module_name", help="name of the module")

    parser.add_argument("-I", metavar="hosts", dest="hosts",
                        default=DEFAULT_HOSTS,
                        help="the name of the inventory hosts file to use")

    parser.add_argument("-i", "--inspect", dest="inspect",
                        action="store_const", const="inspect", default="",
                        help="after running the playbook, open shell that \
                        allows manual inspection of the configuration files, \
                        vaults, and logs")

    parser.add_argument("-p", "--pretty", dest="pretty",
                        action="store_const", const="pretty", default="",
                        help="more information will be output and newlines \
                        will be expanded in that output.")

    parser.add_argument("-v", "--verbose", dest="verbose",
                        action="store_const", const="verbose", default="",
                        help="lots of information will be written to output")

    return parser.parse_args()


def dir_exist(directory):
    """
    Check if a directory exists
    """
    return os.path.isdir(directory)


def module_exist(module_dir, module_name):
    """
    Check if a module(file) exist at a given module directory
    """
    return os.path.isfile(os.path.join(module_dir, module_name))


def playbook_exist(module_dir, playbook):
    """
    Check if the test playbooks exist
    """
    return os.path.isfile(os.path.join(module_dir, "tests", playbook))


def controller(action):
    """
    Start/Stop the testing container environment,
    calls env/controller
    """
    cmd = ' '.join([BASEDIR+"/env/controller", CFG, action])
    proc = Popen(cmd, shell=True, executable="/bin/bash")
    return_code = proc.wait()
    return return_code


def run_tester(inspect, pretty, module_dir, playbook, hosts, verbose):
    """
    Run ansible-tester docker container to start the testing
    """
    # create a empty dir that allows the overlapping volume mount to work
    # e.g. ds-playbooks/irods/library/tests/library
    empty_dir = os.path.join(module_dir, "tests", module_dir.split("/")[-1])
    if not os.path.isdir(empty_dir):
        os.mkdir(empty_dir)

    # docker cmd to run ansible-tester
    cmd = """
    source {0} && \
    (docker run --interactive --rm --tty \
            --env IRODS_HOST="$IRODS_PROVIDER_CONF_HOST" \
            --env IRODS_ZONE_NAME="$IRODS_ZONE_NAME" \
            --env PGHOST="$DBMS_HOST" \
            --network "$DOMAIN" \
            --volume "{1}/tests":/playbooks-under-test:ro \
            --volume "{1}":/playbooks-under-test/{7}:ro \
            ansible-tester "{2}" "{3}" "{4}" "{5}" '' "{6}";
     rmdir {1}/tests/{7})
    """
    cmd = cmd.format(CFG, module_dir, inspect, pretty, verbose, hosts, playbook, module_dir.split("/")[-1])

    proc = Popen(cmd, shell=True, executable="/bin/bash")
    return_code = proc.wait()
    return return_code


if __name__ == "__main__":
    main()
