#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# pylint: disable=invalid-name

"""
This is a mock version of the AMQP message publishing  program having the same
name. It does nothing.

© 2024 The Arizona Board of Regents on behalf of The University of Arizona.
For license information, see https://cyverse.org/license.
"""
