FROM centos:7
MAINTAINER Tony Edgin @ CyVerse

COPY base/config.sh /tmp/base-config
COPY rs/scripts/service.sh.template /tmp/
COPY rs/scripts/prep-svc-script.sh /tmp/prep-svc-script

ARG IRODS_IES=ies
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_PASSWORD=rods
ARG IRODS_ZONE_PORT=1247

RUN /tmp/base-config centos 7 && \
    yum --assumeyes install \
      which \
      ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos7/irods-resource-4.1.10-centos7-x86_64.rpm && \
    /tmp/prep-svc-script && \
    yum clean all && \
    rm --force --recursive /tmp/* /var/cache/yum

COPY base/entrypoint.sh /entrypoint

ENTRYPOINT [ "/entrypoint" ]
CMD [ "/service.sh" ]
