FROM centos:6
MAINTAINER Tony Edgin @ CyVerse

COPY ansible-support/config.sh /tmp/ansible-support
COPY rs/scripts/* /tmp/

ARG IRODS_CONTROL_PLANE_KEY=TEMPORARY__32byte_ctrl_plane_key
ARG IRODS_CONTROL_PLANE_PORT=1248
ARG IRODS_DEFAULT_RESOURCE=demoResc
ARG IRODS_DEFAULT_VAULT=/var/lib/irods/Vault
ARG IRODS_FIRST_EPHEMERAL_PORT=20000
ARG IRODS_HOST=rs
ARG IRODS_IES=ies
ARG IRODS_LAST_EPHEMERAL_PORT=20199
ARG IRODS_NEGOTIATION_KEY=TEMPORARY_32byte_negotiation_key
ARG IRODS_SCHEMA_VALIDATION=https://schemas.irods.org/configuration
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_KEY=TEMPORARY_zone_key
ARG IRODS_ZONE_NAME=tempZone
ARG IRODS_ZONE_PASSWORD=rods
ARG IRODS_ZONE_PORT=1247
ARG IRODS_ZONE_USER=rods

RUN /tmp/ansible-support centos 6 && \
    yum --assumeyes install \
      ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos6/irods-resource-4.1.10-centos6-x86_64.rpm && \
    /tmp/config.sh && \
    yum clean all && \
    rm --force --recursive /tmp/* /var/cache/yum

COPY ansible-support/entrypoint.sh /entrypoint

ENTRYPOINT [ "/entrypoint" ]
CMD [ "/service.sh" ]
