#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# pylint: disable=invalid-name

"""RabbitMQ message publisher for CyVerse Data Store

This script publishes a persistent  message on a given RabbitMQ
exchange. It is intended to be used by the CyVerse Data Store as an
iRODS command script.

Usage:
    amqp-topic-send EXCHANGE KEY BODY

Args:
    EXCHANGE: the RabbitMQ exchange receiving the message
    KEY: the message's routing key
    BODY: the body of the message

Env Var:
    IRODS_AMQP_URI: provides the RabbitMQ broker and credentials to be
        used

© 2024 The Arizona Board of Regents on behalf of The University of
Arizona. For license information, see https://cyverse.org/license.
"""

import os
import sys
from sys import stderr
from typing import List

import pika


def _main(argv: List[str]) -> int:
    try:
        exchange = argv[1]
        key = argv[2]
        body = argv[3]
    except IndexError:
        stderr.write(
            "The exchange, routing key, and message body are required as the first three "
            "parameters, respectively\n")

        return 1

    try:
        uri = os.environ['IRODS_AMQP_URI']
        _publish(uri=uri, exchange=exchange, routing_key=key, body=body)
    except BaseException as e:  # pylint: disable=broad-exception-caught
        stderr.write(f"Failed to publish message: {e} ({type(e)})\n")
        return 1

    return 0


def _publish(uri: str, exchange: str, routing_key: str, body: str) -> None:
    conn_params = pika.URLParameters(uri)
    conn_params.socket_timeout = 10

    with pika.BlockingConnection(conn_params) as conn:
        conn.channel().basic_publish(
            exchange=exchange,
            routing_key=routing_key,
            body=body,
            properties=pika.BasicProperties(delivery_mode=pika.DeliveryMode.Persistent))


if __name__ == '__main__':
    sys.exit(_main(sys.argv))
