#!/usr/bin/env bash
#
# Updates the size of a replication in the ICAT DB. This is called by the
# CyVerse replication logic as part of a workaround for the issue
# https://github.com/irods/irods/issues/5160.
#
# Usage:
#   correct-size ID REPL-NUM SIZE
#
# Arguments:
#   ID        the DB Id of the data object to modify
#   REPL-NUM  the data object's replica number whose size will be set
#   SIZE      the new size of the replica
#
# © 2024 The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

set -o errexit -o nounset -o pipefail


main() {
	if (( $# < 3 )); then
		printf 'The the data object id, replica number, and size are required.' >&2
		return 1
	fi

	local id="$1"
	local replNum="$2"
	local size="$3"

	iadmin modrepl data_id "$id" repl_num "$replNum" DATA_SIZE "$size"
}


main "$@"
