#!/bin/bash
#
# Creates an archival collection as a given user for a given DE app execution 
# and gives the user read access the corresponding staging collection.
#
# USAGE:
#  de-create-collection clientUser stagePath archivePath execId appId
#
# PARAMETERS:
#  clientUser   The iRODS user creating the archival collection
#  stagePath    The absolute path to the associated staging collection
#  archivePath  The absolute path to the archival collection
#  execId       The Id of the DE app execution that generated the staged data
#  appId        The Id of the DE app that was executed

set -o errexit -o nounset -o pipefail


main() {
  if [[ "$#" -lt 5 ]]
  then
    printf 'Too few input parameters\n' >&2
    return 1
  fi

  local clientUser="$1"
  local stagePath="$2"
  local archivePath="$3"
  local execId="$4"
  local appId="$5"

  if ! clientUserName="$clientUser" imkdir -p "$archivePath"
  then
    return 1
  fi

  local exitStatus=0

  if ! ichmod -M read "$clientUser" "$stagePath"
  then
    printf 'Unable to give %s read access to %s\n' "$clientUser" "$stagePath" >&2
    exitStatus=1
  fi

  local kvs
  kvs=$(query_kvs "$archivePath")

  if [[ "$kvs" =~ CAT_NO_ROWS_FOUND: ]]
  then
    kvs=
  fi

  local execKV=ipc-execution-id="$execId"

  if ! [[ "$kvs" =~ $execKV ]]
  then
    if ! imeta adda -C "$archivePath" ipc-execution-id "$execId" UUID
    then
      printf 'Unable to assign execution Id %s to collection %s\n' "$execId" "$archivePath" >&2
      exitStatus=1
    fi
  fi

  local appKV=ipc-analysis-id="$appId"

  if ! [[ "$kvs" =~ $appKV ]]
  then
    if ! imeta adda -C "$archivePath" ipc-analysis-id "$appId" UUID
    then
      printf 'Unable to assign app Id %s to collection %s\n' "$appId" "$archivePath" >&2
      exitStatus=1
    fi
  fi

  return $exitStatus
}


query_kvs() {
  local collPath="$1"

  iquest '%s=%s' "select META_COLL_ATTR_NAME, META_COLL_ATTR_VALUE where COLL_NAME = '$collPath'" \
    2> /dev/null
}


main "$@"
