#!/usr/bin/env bash
#
# Removes a rule from the rule queue.
#
# Usage:
#  deleted-scheduled-rule RULE-ID
#
# Arguments:
#  RULE-ID  The Id of the rule to dequeue
#
# © 2024 The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.


main()
{
  if [ "$#" -lt 1 ]
  then
    printf 'The Id of the rule to dequeue must be provided\n' >&2
    return 1
  fi

  local ruleId="$1"

  iqdel "$ruleId"
}


set -e
main "$@"
