#!/usr/bin/env bash
#
# Assigns a UUID to a collection or data object.
#
# USAGE:
#  set-uuid type path uuid
#
# PARAMETERS:
#  type  The type of entity receiving the UUID: `-C` for collection or `-d` for
#        data object.
#  path  The absolute path to the entity receiving the UUID.
#  uuid  The UUID being assigned.

# XXX - This is a workaround for https://github.com/irods/irods/issues/3437. It is still present in
#       4.2.8.

set -e

readonly COLL_TYPE='-C'
readonly DATA_TYPE='-d'


main()
{
  if [ "$#" -lt 1 ]
  then
    printf 'The type of the entity being given a UUID needs to be provided\n' >&2
    return 1
  fi

  if [ "$#" -lt 2 ]
  then
    printf 'The absolute path to the entity needs to be provided\n' >&2
    return 1
  fi

  if [ "$#" -lt 3 ]
  then
    printf 'The UUID to assign needs to be provided\n' >&2
    return 1
  fi

  local type="$1"
  local path="$2"
  local uuid="$3"

  if [[ "${type^^}" == "$COLL_TYPE" ]]
  then
    type="$COLL_TYPE"
  elif [[ "${type,,}" == "$DATA_TYPE" ]]
  then
    type="$DATA_TYPE"
  else
    printf 'The entity type must be "%s" for a collection or "%s" for a data object.\n' \
        "$COLL_TYPE" "$DATA_TYPE" \
      >&2

    return 1
  fi

  imeta set "$type" "$path" ipc_UUID "$uuid"
}


main "$@"
