---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Create HAProxy instance
      ansible.builtin.include_role:
        name: haproxy
      vars:
        haproxy_restart_allowed: true
