---
- name: Prepare
  hosts: all
  tasks:
    - name: Prepare | update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Prepare | install required packages
      ansible.builtin.package:
        name:
          - python-is-python3
          - python3-netaddr
          - rsyslog
        state: present
