FROM test-env-base:ubuntu1804

ARG IRODS_CATALOG_PROVIDER=csp
ARG IRODS_CONTROL_PLANE_KEY=TEMPORARY__32byte_ctrl_plane_key
ARG IRODS_CONTROL_PLANE_PORT=1248
ARG IRODS_DEFAULT_RESOURCE=demoResc
ARG IRODS_DEFAULT_VAULT=/var/lib/irods/Vault
ARG IRODS_FIRST_EPHEMERAL_PORT=20000
ARG IRODS_HOST=rs
ARG IRODS_LAST_EPHEMERAL_PORT=20199
ARG IRODS_NEGOTIATION_KEY=TEMPORARY_32byte_negotiation_key
ARG IRODS_SCHEMA_VALIDATION=https://schemas.irods.org/configuration
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_KEY=TEMPORARY_zone_key
ARG IRODS_ZONE_NAME=tempZone
ARG IRODS_ZONE_PASSWORD=rods
ARG IRODS_ZONE_PORT=1247
ARG IRODS_ZONE_USER=rods

ARG DEBIAN_FRONTEND=noninteractive

ADD --chmod=444 \
	https://packages.irods.org/irods-signing-key.asc /etc/apt/trusted.gpg.d/irods-signing-key.asc

RUN \
	--mount=target=/tmp/config-irods,source=irods-consumer/scripts/config-irods.sh \
	--mount=target=/tmp/service.sh.template,source=irods-consumer/scripts/service.sh.template \
	--mount=target=/tmp/prep-svc-script,source=irods-consumer/scripts/prep-svc-script.sh \
<<EOF
	set -o errexit

### Install iRODS
	printf 'deb [arch=amd64] https://packages.irods.org/apt/ %s main\n' \
			"$(lsb_release --codename --short)" \
		> /etc/apt/sources.list.d/renci-irods.list
	printf 'Package: irods-*\nPin: version 4.2.8\nPin-Priority: 1001\n' \
		> /etc/apt/preferences.d/irods
	apt-get update
	apt-get --yes install irods-server
	python3 -m pip install python-irodsclient

### Configure iRODS
	# NOTE: For 4.2.8
	python3 -m pip install psutil
	# ^^^ 4.2.8
	/tmp/config-irods

### Create service script
	/tmp/prep-svc-script

### Clean apt cache
	apt-get clean autoclean
	rm --force --recursive /var/lib/apt/lists/*
EOF

CMD [ "/service.sh" ]
