FROM test-env-base:ubuntu1804

ARG IRODS_CATALOG_PROVIDER=csp
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_PASSWORD=rods
ARG IRODS_ZONE_PORT=1247

# Create service script
RUN \
	--mount=target=/tmp/service.sh.template,source=irods-provider/scripts/service.sh.template \
	--mount=target=/tmp/prep-svc-script,source=irods-provider/scripts/prep-svc-script.sh \
	/tmp/prep-svc-script

CMD [ "/service.sh" ]
