FROM test-env-base:centos7

ARG IRODS_CATALOG_PROVIDER=csp
ARG IRODS_CONTROL_PLANE_KEY=TEMPORARY__32byte_ctrl_plane_key
ARG IRODS_CONTROL_PLANE_PORT=1248
ARG IRODS_DEFAULT_RESOURCE=demoResc
ARG IRODS_DEFAULT_VAULT=/var/lib/irods/Vault
ARG IRODS_FIRST_EPHEMERAL_PORT=20000
ARG IRODS_HOST=rs
ARG IRODS_LAST_EPHEMERAL_PORT=20199
ARG IRODS_NEGOTIATION_KEY=TEMPORARY_32byte_negotiation_key
ARG IRODS_SCHEMA_VALIDATION=https://schemas.irods.org/configuration
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_KEY=TEMPORARY_zone_key
ARG IRODS_ZONE_NAME=tempZone
ARG IRODS_ZONE_PASSWORD=rods
ARG IRODS_ZONE_PORT=1247
ARG IRODS_ZONE_USER=rods

ADD https://packages.irods.org/renci-irods.yum.repo /etc/yum.repos.d/renci-irods.yum.repo

RUN \
	--mount=target=/tmp/config-irods,source=irods-consumer/scripts/config-irods.sh \
	--mount=target=/tmp/service.sh.template,source=irods-consumer/scripts/service.sh.template \
	--mount=target=/tmp/prep-svc-script,source=irods-consumer/scripts/prep-svc-script.sh \
<<EOF
	set -o errexit

### Install iRODS
	rpm --import https://packages.irods.org/irods-signing-key.asc
	yum --assumeyes versionlock add irods-*-4.3.1
	yum --assumeyes install irods-server
# XXX - irods-icommands required by irods-server but not installed by dependency resolution in
#       CentOS 7
	yum --assumeyes install irods-icommands
# XXX - ^^^
	python3 -m pip install python-irodsclient

### Configure iRODS
	/tmp/config-irods

### Create service script
	/tmp/prep-svc-script

### Populate .ssh/authorized_keys
	echo ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMNAkCWfBgthPFt3580sM8H0BXpCQVrEI8Y2Kpq9bO+3 disallowed \
		> /root/.ssh/authorized_keys

### Clean yum cache
	yum clean all
	rm --force --recursive /var/cache/yum
EOF

CMD [ "/service.sh" ]
