FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN --mount=target=/tmp/config,source=base/config.sh /tmp/config ubuntu 20.04

COPY base/entrypoint.sh /entrypoint

ENTRYPOINT [ "/entrypoint" ]
