---
- name: Set up RabbitMQ broker
  hosts: amqp
  become: true
  roles:
    - role: rabbitmq
      vars:
        rabbitmq_admin_username: "{{ _admin_username }}"
        rabbitmq_admin_password: "{{ _admin_password }}"
        rabbitmq_broker_port: "{{ _broker_port }}"
        rabbitmq_mgmt_port: "{{ _management_port }}"
