---
- name: Disable SELinux
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tasks:
    - name: Disable SELinux
      when: ansible_selinux.status == "enabled"
      ansible.posix.selinux:
        state: disabled
  tags:
    - no_testing
