---
- name: install ansible core facts requirement
  hosts: all:!unmanaged_systems:!localhost
  become: true
  gather_facts: false
  tasks:
    - name: install dmidecode support
      package:
        name: dmidecode
        state: present
        use: "{{ _package_manager }}"


- name: install required packages for ansible
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tasks:
    - name: update apt cache on Ubuntu machines
      when: ansible_distribution == 'Ubuntu'
      apt:
        update_cache: true
      tags:
        - non_idempotent

    - name: install EPEL repository on CentOS machines
      when: ansible_distribution == 'CentOS'
      package:
        name: epel-release
        state: present

    - name: install packages
      package:
        name:
          - "{{ 'iproute2' if ansible_distribution == 'Ubuntu' else 'iproute' }}"
          - jq
          - python3
          - "{{ 'python3-dns' if ansible_distribution == 'Ubuntu' else 'python-dns' }}"
          - python3-pip
          - "{{ 'python3-requests' if ansible_distribution == 'Ubuntu' else 'python-requests' }}"
          - "{{ 'python3-selinux' if ansible_distribution == 'Ubuntu' else 'libselinux-python' }}"
          - >-
            {{ 'python3-virtualenv' if ansible_distribution == 'Ubuntu' else 'python-virtualenv' }}
        state: present

    - name: install pip2 on CentOS machines
      when: ansible_distribution == 'CentOS'
      package:
       name: python2-pip
       state: present

    - name: install yum-plugin-versionlock on CentOS machines
      when: ansible_distribution == 'CentOS'
      package:
        name: yum-plugin-versionlock
        state: present

    - name: Install python-is-python3 on Ubuntu 22.04 machines
      when: >-
        ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('22.04', '>=')
      package:
        name: python-is-python3
        state: present

- name: remove packages on ubuntu
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tasks:
    - name: remove unattended-upgrades on Ubuntu machines
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: unattended-upgrades
        state: absent
      tags:
        - idempotent
