- name: Ensure rng-tools is installed
  hosts: all:!unmanaged_systems:!localhost
  become: yes
  tasks:
    - name: Install rng-tools package
      ansible.builtin.package:
        name: rng-tools
        state: present
