---
- name: initialize iptables
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tasks:
    - name: update apt cache on Ubuntu machines
      when: ansible_distribution == 'Ubuntu'
      apt:
        update_cache: true
      tags:
        - non_idempotent

    - name: install iptables package
      package:
        name: >-
          {{ 'iptables-persistent' if ansible_distribution == 'Ubuntu' else
            'iptables-services' }}
        state: present
