---
- name: Set up mail for sending alerts
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tasks:
    - name: Update package repository
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.apt:
        update_cache: true
      tags: non_idempotent

    - name: Install sendmail
      ansible.builtin.package:
        name: sendmail
        state: present

    - name: Configure sendmail
      when: inventory_hostname | ansible.utils.ipaddr
      block:
        - name: Install m4
          ansible.builtin.package:
            name: m4
            state: present

        - name: Install sendmail config
          ansible.builtin.package:
            name: sendmail-cf
            state: present

        - name: Configure masquerading
          ansible.builtin.blockinfile:
            path: /etc/mail/sendmail.mc
            marker: dnl {mark} DS MANAGED BLOCK
            block: |
              FEATURE(masquerade_envelope)dnl
              MASQUERADE_AS({{ _mail_domain_name }})dnl
              MASQUERADE_DOMAIN({{ ansible_fqdn }})dnl

        - name: Rebuild sendmail config
          ansible.builtin.shell:
            executable: /bin/bash
            cmd: |
              mc=/etc/mail/sendmail.mc
              cf=/etc/mail/sendmail.cf
              newCf="$cf".new
              if [[ "$cf" -ot "$mc" ]]; then
                if ! m4 "$mc" > "$newCf"; then
                  rm --force "$newCf"
                  exit 1
                fi
                if diff --brief "$newCf" "$cf" > /dev/null; then
                  rm --force "$newCf"
                  exit 0
                fi
                if ! mv --force "$newCf" "$cf"; then
                  exit 1
                fi
                echo changed
              fi
          register: response
          changed_when: response.stdout == 'changed'
          notify: Restart sendmail

  handlers:
    - name: Restart sendmail
      ansible.builtin.service:
        name: sendmail
        state: restarted
