---
- name: Upgrade system packages
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tags:
    - non_idempotent
  tasks:
    - name: Update apt cache on Ubuntu machines
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade system packages
      ansible.builtin.package:
        name: '*'
        state: latest  # noqa package-latest
      register: result


- name: Reboot changed nodes
  when: result is changed and _reboot_on_pkg_change
  ansible.builtin.import_playbook: reboot.yml
  tags:
    - non_idempotent
