---
- name: Converge
  hosts: all
  tasks:
    - name: Include cyverse.rabbitmq
      ansible.builtin.include_role:
        name: cyverse.rabbitmq
      vars:
        rabbitmq_mgmt_port: "{{ mgmt_port }}"
        rabbitmq_admin_username: "{{ admin_user }}"
        rabbitmq_admin_password: "{{ admin_passwd }}"
