---
- name: Install CentOS | epel repository
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Install CentOS | ensure erlang-erts isn't installed
  ansible.builtin.package:
    name: erlang-erts
    state: absent

- name: Install CentOS | erlang (stripped-down rabbitmq-provided RPM)
  when: ansible_distribution == 'CentOS'
  ansible.builtin.yum:
    name: >-
      https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.7/erlang-23.2.7-1.el7.x86_64.rpm

- name: Install CentOS | from web
  when: ansible_distribution == 'CentOS'
  ansible.builtin.yum:
    name: >-
      https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.14/rabbitmq-server-3.8.14-1.el7.noarch.rpm
