---
- name: Install | install CA certificates for get_url
  ansible.builtin.apt:
    name: ca-certificates
    update_cache: true
    state: present

- name: Install | team RabbitMQ main signing key
  ansible.builtin.get_url:
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
    dest: /usr/share/keyrings/com.rabbitmq.team.asc
    mode: u+r

- name: Install | community mirror of Cloudsmith modern Erlang repository
  ansible.builtin.get_url:
    url: >-
      https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
    dest: /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc
    mode: u+r

- name: Install | community mirror of Cloudsmith modern RabbitMQ repository
  ansible.builtin.get_url:
    url: >-
      https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
    dest: /usr/share/keyrings/rabbitmq.9F4587F226208342.asc
    mode: u+r

- name: Install | add apt repositories maintained by Team RabbitMQ
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/rabbitmq.list
    content: |
      ## Provides modern Erlang/OTP releases
      ##
      deb [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ ansible_facts['lsb']['codename'] }} main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ ansible_facts['lsb']['codename'] }} main

      # another mirror for redundancy
      deb [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa2.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ ansible_facts['lsb']['codename'] }} main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa2.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ ansible_facts['lsb']['codename'] }} main

      ## Provides RabbitMQ
      ##
      deb [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu {{ ansible_facts['lsb']['codename'] }} main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu {{ ansible_facts['lsb']['codename'] }} main

      # another mirror for redundancy
      deb [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa2.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu {{ ansible_facts['lsb']['codename'] }} main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa2.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu {{ ansible_facts['lsb']['codename'] }} main
    mode: u+r

- name: Install | Erlang and RabbitMQ
  ansible.builtin.apt:
    name:
      - 'erlang-base=1:25.1.2-1'
      - 'erlang-asn1=1:25.1.2-1'
      - 'erlang-crypto=1:25.1.2-1'
      - 'erlang-eldap=1:25.1.2-1'
      - 'erlang-ftp=1:25.1.2-1'
      - 'erlang-inets=1:25.1.2-1'
      - 'erlang-mnesia=1:25.1.2-1'
      - 'erlang-os-mon=1:25.1.2-1'
      - 'erlang-parsetools=1:25.1.2-1'
      - 'erlang-public-key=1:25.1.2-1'
      - 'erlang-runtime-tools=1:25.1.2-1'
      - 'erlang-snmp=1:25.1.2-1'
      - 'erlang-ssl=1:25.1.2-1'
      - 'erlang-syntax-tools=1:25.1.2-1'
      - 'erlang-tftp=1:25.1.2-1'
      - 'erlang-tools=1:25.1.2-1'
      - 'erlang-xmerl=1:25.1.2-1'
      - 'rabbitmq-server=3.11.23-1'
    update_cache: true
    state: fixed

- name: Install | pin Erlang version
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/erlang
    content: |
      Package: erlang*
      Pin: version 1:25.1.2-1
      Pin-Priority: 1001
    mode: u+r

- name: Install | pin RabbitMQ version
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/rabbitmq
    content: |
      Package: rabbitmq-server
      Pin: version 3.11.23-1
      Pin-Priority: 1001
    mode: u+r
