---
- name: Install | detect old RabbitMQ repo
  shell:
    executable: /bin/bash
    cmd: |
      if \
        [[ -e /etc/apt/sources.list.d/rabbitmq.list ]] \
        && ! grep --quiet 'com.rabbitmq.team.gpg' /etc/apt/sources.list.d/rabbitmq.list
      then
        echo old
      fi
  register: resp
  changed_when: false

- name: Install | removed old RabbitMQ repo
  when: resp.stdout == 'old'
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/rabbitmq.list
    - /usr/share/keyrings/rabbitmq.9F4587F226208342.asc
    - /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc
    - /usr/share/keyrings/com.rabbitmq.team.asc

- name: Install | install CA certificates for get_url
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    update_cache: true
    state: present

- name: Install | team RabbitMQ main signing key
  ansible.builtin.shell:
    executable: /bin/bash
    creates: /usr/share/keyrings/com.rabbitmq.team.gpg
    cmd: |
      set -o pipefail
      curl --fail --location --silent --tlsv1 \
          https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA \
        | gpg --dearmor \
        > /usr/share/keyrings/com.rabbitmq.team.gpg

- name: Install | add apt repositories maintained by Team RabbitMQ
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/rabbitmq.list
    mode: u+r
    content: |
      ## Modern Erlang/OTP releases
      ##
      deb [arch=amd64 signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://deb1.rabbitmq.com/rabbitmq-erlang/ubuntu/jammy jammy main
      deb [arch=amd64 signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://deb2.rabbitmq.com/rabbitmq-erlang/ubuntu/jammy jammy main

      ## Provides modern RabbitMQ releases
      ##
      deb [arch=amd64 signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://deb1.rabbitmq.com/rabbitmq-server/ubuntu/jammy jammy main
      deb [arch=amd64 signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://deb2.rabbitmq.com/rabbitmq-server/ubuntu/jammy jammy main

- name: Install | Erlang and RabbitMQ
  ansible.builtin.apt:
    name:
      - 'erlang-base=1:25.1.2-1'
      - 'erlang-asn1=1:25.1.2-1'
      - 'erlang-crypto=1:25.1.2-1'
      - 'erlang-eldap=1:25.1.2-1'
      - 'erlang-ftp=1:25.1.2-1'
      - 'erlang-inets=1:25.1.2-1'
      - 'erlang-mnesia=1:25.1.2-1'
      - 'erlang-os-mon=1:25.1.2-1'
      - 'erlang-parsetools=1:25.1.2-1'
      - 'erlang-public-key=1:25.1.2-1'
      - 'erlang-runtime-tools=1:25.1.2-1'
      - 'erlang-snmp=1:25.1.2-1'
      - 'erlang-ssl=1:25.1.2-1'
      - 'erlang-syntax-tools=1:25.1.2-1'
      - 'erlang-tftp=1:25.1.2-1'
      - 'erlang-tools=1:25.1.2-1'
      - 'erlang-xmerl=1:25.1.2-1'
      - 'rabbitmq-server=3.11.23-1'
    update_cache: true
    state: fixed

- name: Install | pin Erlang version
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/erlang
    content: |
      Package: erlang*
      Pin: version 1:25.1.2-1
      Pin-Priority: 1001
    mode: u+r

- name: Install | pin RabbitMQ version
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/rabbitmq
    content: |
      Package: rabbitmq-server
      Pin: version 3.11.23-1
      Pin-Priority: 1001
    mode: u+r
