#!/usr/bin/env bash
#
# Create a collection
#
# Usage: md-repo-mkdir SVC-ACNT COLL
#
# SVC-ACNT is the iRODS account used by the MD Repo service. COLL is the
# absolute path to the collection that will be created.
#
# This script creates a collection so that a person uploading a folder into MD
# Repo can use an iRODS ticket to create a collection. By creating a collection
# as part of the iRODS upload rule logic, the collection will exist at the time
# of upload and be overwritten. This is a work around for the bug in iRODS 4.2.8
# that prevents collections from being created via ticket.

set -o errexit -o nounset -o pipefail

main() {
	if (( $# < 2 )); then
		printf 'The MD Repo service account and the absolute path to the collection are required.\n' \
			>&2

		return 1
	fi

	local mdRepoAcnt="$1"
	local coll="$2"

	if [[ "$coll" =~ ^[^/] ]]; then
		printf 'The absolute path to the collection is required.\n' >&2
		return 1
	fi

	clientUserName="$mdRepoAcnt" imkdir "$coll"
}

main "$@"
