#!/usr/bin/env bash
#
# Create an empty data object
#
# Usage: md-repo-touch-obj SVC_ACNT DATA_PATH
#
# SVC_ACNT is the iRODS account used by the MD Repo service. -DATA_PATH is the
# absolute path to the data object that will be created.
#
# This script creates an empty data object so that a person uploading data into
# MD Repo can use an iRODS ticket to create a data object. By creating an empty
# data object as part of the iRODS upload rule logic, the data object will exist
# at the time of upload and be overwritten. This is a work around for the bug in
# iRODS 4.2.7 - 4.2.11 that prevents data objects from being created via ticket.
#
# © 2025 The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

set -o errexit -o nounset -o pipefail

main() {
	if (( $# < 2 )); then
		printf \
				'The MD Repo service account and the absolute path to the data object are required.\n' \
			>&2

		return 1
	fi

	local mdRepoAcnt="$1"
	local dataObj="$2"

	if [[ "$dataObj" =~ ^[^/] ]]; then
		printf 'The absolute path to the data object is required.\n' >&2
		return 1
	fi

	touch /tmp/md-repo-empty-file
	clientUserName="$mdRepoAcnt" iput /tmp/md-repo-empty-file "$dataObj"
}

main "$@"
