---
- name: Set up HAProxy
  hosts: proxy
  become: true
  roles:
    - role: haproxy
      vars:
        haproxy_block_client_lost: "{{ proxy_block_client_list }}"
        # Reserve two CPUs for OS
        haproxy_num_threads: "{{ [ ansible_processor_vcpus - 2, 1 ] | max }}"
        haproxy_queue_timeout: 10m
        haproxy_restart_allowed: "{{ _restart_allowed }}"
        haproxy_rsyslog_conf: "{{ _rsyslog_conf }}"
        haproxy_stats_tls_crt: "{{ _stats_tls_crt }}"
        haproxy_stats_tls_crt_content: "{{ _stats_tls_crt_content }}"
        haproxy_stats_auth: "{{ _stats_auth }}"
        haproxy_irods_reconn_ports: "{{ _irods_reconn_ports }}"
        haproxy_irods_host: "{{ groups['irods_catalog'][0] }}"
        haproxy_irods_direct_max_conn: "{{ _irods_direct_max_conn }}"
        haproxy_irods_throttled_max_conn: 100
        haproxy_irods_vip_client_hosts: "{{ _irods_vip_client_hosts }}"
        haproxy_webdav_hosts: "{{ groups['webdav'] }}"
        haproxy_webdav_check_period: 6s
        haproxy_sftp_hosts: "{{ groups['sftp'] }}"
        haproxy_sftp_port: "{{ _sftp_port }}"
        haproxy_sftp_backend_port: "{{ _sftp_backend_port }}"
        haproxy_sftp_check_period: 6s
