---
- name: Set up HAProxy
  hosts: proxy
  become: true
  roles:
    - role: haproxy
      vars:
        # Reserve two CPUs for OS
        haproxy_num_threads: "{{ [ ansible_processor_vcpus - 2, 1 ] | max }}"
        haproxy_queue_timeout: 10m
        haproxy_rsyslog_conf: "{{ proxy_rsyslog_conf }}"
        haproxy_stats_tls_crt: "{{ proxy_stats_tls_crt }}"
        haproxy_stats_tls_crt_content: "{{ proxy_stats_tls_crt_content }}"
        haproxy_stats_auth: "{{ proxy_stats_auth }}"
        haproxy_irods_reconn_ports: "{{ proxy_irods_reconn_ports }}"
        haproxy_irods_host: "{{ groups['irods_catalog'][0] }}"
        haproxy_irods_direct_max_conn: "{{ proxy_irods_direct_max_conn }}"
        haproxy_irods_throttled_max_conn: 100
        haproxy_irods_vip_client_hosts: "{{ proxy_irods_vip_client_hosts }}"
        haproxy_webdav_hosts: "{{ groups['webdav'] }}"
        haproxy_webdav_check_period: 6s
        haproxy_sftp_hosts: "{{ groups['sftp'] }}"
        haproxy_sftp_port: "{{ proxy_sftp_port }}"
        haproxy_sftp_backend_port: "{{ proxy_sftp_backend_port }}"
        haproxy_sftp_check_period: 6s
