---
- name: Restore all client access
  hosts: proxy
  become: true
  tags:
    - no_testing
  tasks:
    - name: Enable iRODS access
      community.general.haproxy:
        backend: irods_direct
        host: irods
        state: enabled
        fail_on_not_found: true

    - name: Enable WebDAV access
      community.general.haproxy:
        backend: webdavs
        host: dav
        state: enabled
        fail_on_not_found: true

    - name: Enable SFTP access
      community.general.haproxy:
        backend: sftp
        host: sftp
        state: enabled
        fail_on_not_found: true
