FROM test-env-base:ubuntu2004

ARG DB_NAME=ICAT
ARG DB_PASSWORD=testpassword
ARG DB_USER=irods
ARG DBMS_PORT=5432
ARG IRODS_DELAY_SERVER=csp
ARG IRODS_RESOURCES=demoResc:rs:/var/lib/irods/Vault
ARG IRODS_ZONE_NAME=tempZone
ARG IRODS_ZONE_PASSWORD=rods
ARG IRODS_ZONE_USER=rods

ARG DEBIAN_FRONTEND=noninteractive
ARG LC_COLLATE=C

RUN <<EOF
	set -o errexit
	apt-get update
	apt-get install --yes locales
	locale-gen en_US.UTF-8
	apt-get install --yes postgresql postgresql-client python3-psycopg2
	apt-get clean autoclean
	rm --force --recursive /var/lib/apt/lists/*
EOF

COPY --chown=postgres:postgres postgresql/config/* /etc/postgresql/12/main/

USER postgres

RUN \
	--mount=target=/tmp/icat.sql.template,source=postgresql/scripts/icat.sql.template \
	--mount=target=/tmp/config,source=postgresql/scripts/config.sh \
	/tmp/config

USER root

COPY postgresql/service.sh /

CMD [ "/service.sh" ]
