---
- name: Create storage resources
  ansible.builtin.import_playbook: irods_storage_resources.yml


- name: Configure iRODS for Avra
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - name: Configured iRODS for Avra
      when: _avra_base_collection != ''
      block:
        - name: Create avra resource
          irods_resource_hierarchy:
            hierarchy: "{{ _avra_resource_hierarchy }}"

        - name: Create project collection
          delegate_to: localhost
          become: false
          irods_collection:
            path: "{{ _avra_base_collection }}"
            parents: true
            state: present
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"

        - name: Assign owner to project collection
          delegate_to: localhost
          become: false
          irods_permission:
            subject: "{{ _avra_manager }}"
            permission: own
            object: "{{ _avra_base_collection }}"
            recursive: true
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"

        - name: Assign project collection to Avra resource
          delegate_to: localhost
          become: false
          irods_avu:
            entity_type: resource
            entity_name: "{{ _avra_resource_hierarchy.name }}"
            attribute: ipc::hosted-collection
            value: "{{ _avra_base_collection }}"
            units: required
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            zone: "{{ _irods_zone_name }}"
            username: "{{ _irods_clerver_user }}"
            password: "{{ _irods_clerver_password }}"
