---
- name: Remove BisQue support
  hosts: irods_catalog
  strategy: linear
  become: true
  tasks:
    - name: Remove bisque files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/irods/bisque.re
        - /etc/irods/bisque-env.re
        - /var/lib/irods/.bisque
        - /var/lib/irods/msiExecCmd_bin/bisque_paths.py
        - /var/lib/irods/msiExecCmd_bin/url-encode-path-segments.sh

    - name: Remove bisque user  # noqa: run-once[task]
      run_once: true
      delegate_to: localhost
      become: false
      irods_user:
        zone: "{{ _irods_zone_name }}"
        name: bisque
        state: absent
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
