---
- name: prepare for bisque_paths
  hosts: irods_catalog
  become: true
  tasks:
    - name: install urlencode
      package:
        name: gridsite-clients
        state: present

    - name: ensure /var/log/bisque exists
      file:
        path: /var/log/bisque
        state: directory
        owner: "{{ _irods_service_account_name }}"
        group: "{{ _irods_service_group_name }}"
        mode: u=rwx


- name: configure bisque client
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: install bisque_paths.py
      get_url:
        validate_certs: false
        url: https://gitlab.cyverse.org/ds/bisque_support/raw/master/bisque_paths/bisque_paths.py
        dest: /var/lib/irods/msiExecCmd_bin
        mode: u+rx

    - name: place .bisque
      when: _bisque_url|length > 0
      template:
        src: templates/bisque.j2
        dest: "{{ ansible_env.HOME }}/.bisque"
        mode: u=r

    - name: install url-encode-path-segments command script
      copy:
        src: files/bisque/var/lib/irods/msiExecCmd_bin/url-encode-path-segments.sh
        dest: /var/lib/irods/msiExecCmd_bin
        mode: u+rx

    - name: place BisQue rule logic
      copy:
        src: files/rule-bases/bisque.re
        dest: /etc/irods/bisque.re
        mode: u+r
      notify: reload rules

  handlers:
    - name: reload rules
      file:
        path: /etc/irods/core.re
        state: touch
        mode: u+r
