---
- name: Prepare for bisque-paths
  hosts: irods_catalog
  become: true
  tasks:
    - name: Install urlencode
      ansible.builtin.package:
        name: gridsite-clients
        state: present

    - name: Ensure /var/log/bisque exists
      ansible.builtin.file:
        path: /var/log/bisque
        state: directory
        owner: "{{ _irods_service_account_name }}"
        group: "{{ _irods_service_group_name }}"
        mode: u=rwx


- name: Configure bisque client
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: Place .bisque
      when: _bisque_url | length > 0
      ansible.builtin.template:
        src: templates/bisque.j2
        dest: "{{ ansible_env.HOME }}/.bisque"
        mode: u=r

    - name: Install bisque-paths
      ansible.builtin.get_url:
        validate_certs: false
        url: https://gitlab.cyverse.org/ds/bisque_support/raw/master/bisque_paths/bisque_paths.py
        dest: /var/lib/irods/msiExecCmd_bin/bisque-paths
        mode: u+rx

    - name: Install url-encode-path-segments command script
      ansible.builtin.copy:
        src: files/bisque/var/lib/irods/msiExecCmd_bin/url-encode-path-segments
        dest: /var/lib/irods/msiExecCmd_bin
        mode: u+rx

    - name: Place BisQue rule logic
      ansible.builtin.copy:
        src: files/rule-bases/bisque.re
        dest: /etc/irods/bisque.re
        mode: u+r
      notify: Reload rules

  post_tasks:
    - name: Remove obsolete command scripts
      ansible.builtin.file:
        path: /var/lib/irods/msiExecCmd_bin/{{ item }}
        state: absent
      loop:
        - bisque_paths.py
        - url-encode-path-segments.sh

  handlers:
    - name: Reload rules
      ansible.builtin.file:
        path: /etc/irods/core.re
        state: touch
        mode: u+r
