---
- name: Remove BisQue files
  hosts: irods
  become: true
  tasks:
    - name: Remove bisque files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/irods/bisque.re
        - /etc/irods/bisque-env.re
        - /var/lib/irods/.bisque
        - /var/lib/irods/msiExecCmd_bin/bisque_paths.py
        - /var/lib/irods/msiExecCmd_bin/url-encode-path-segments.sh


- name: Remove BisQue user
  hosts: irods_catalog
  run_once: true
  gather_facts: false
  tasks:
    - name: Remove bisque user
      delegate_to: localhost
      irods_user:
        zone: "{{ _irods_zone_name }}"
        name: bisque
        state: absent
        force: true
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
