---
- name: Make storage resources
  ansible.builtin.import_playbook: mk_storage_resources.yml


- name: Configure iRODS for Cereus
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - name: Create cereus resource
      irods_resource_hierarchy:
        hierarchy: "{{ _cereus_resource_hierarchy }}"

    - name: Assign collection to Cereus resource
      delegate_to: localhost
      become: false
      no_log: true
      irods_avu:
        entity_type: resource
        entity_name: "{{ _cereus_resource_hierarchy.name }}"
        attribute: ipc::hosted-collection
        value: "{{ item }}"
        units: preferred
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        zone: "{{ _irods_zone_name }}"
        username: "{{ _irods_clerver_user }}"
        password: "{{ _irods_clerver_password }}"
      with_items: "{{ _cereus_collections }}"
