---
- name: Customize for DE
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - name: Delete jobs staging collection
      delegate_to: localhost
      become: false
      irods_collection:
        path: /{{ _irods_zone_name }}/jobs
        state: absent
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: Delete user for DE jobs
      delegate_to: localhost
      become: false
      irods_user:
        name: "{{ _de_job_irods_user }}"
        state: absent
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"
