---
- name: Run-time initialization
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - name: Ensure service user type exists
      irods_user_type:
        type: ds-service
        description: a Data Store service

    - name: Ensure public group's home is correct
      become: false
      delegate_to: localhost
      irods_move:
        source: /{{ _irods_zone_name }}/home/public
        destination: /{{ _irods_zone_name }}/home/shared
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: Ensure public group's trash is correct
      become: false
      delegate_to: localhost
      irods_move:
        source: /{{ _irods_zone_name }}/trash/home/public
        destination: /{{ _irods_zone_name }}/trash/home/shared
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: Ensure CyVerse curated collection base collection exists
      become: false
      delegate_to: localhost
      irods_collection:
        path: /{{ _irods_zone_name }}/home/shared/commons_repo/curated
        parents: true
        state: present
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: Ensure predefined collections have UUIDs
      become: false
      delegate_to: localhost
      irods_avu:
        entity_type: collection
        entity_name: "{{ item }}"
        attribute: ipc_UUID
        value: "{{ lookup('uuid', 1) }}" #  for time-based UUID
        host: "{{ groups['irods_catalog'][0] }}"
        zone: "{{ _irods_zone_name }}"
        username: "{{ _irods_clerver_user }}"
        password: "{{ _irods_clerver_password }}"
      loop:
        - /{{ _irods_zone_name }}
        - /{{ _irods_zone_name }}/home
        - /{{ _irods_zone_name }}/home/{{ _irods_clerver_user }}
        - /{{ _irods_zone_name }}/home/shared
        - /{{ _irods_zone_name }}/trash
        - /{{ _irods_zone_name }}/trash/home
        - /{{ _irods_zone_name }}/trash/home/{{ _irods_clerver_user }}
        - /{{ _irods_zone_name }}/trash/home/shared


    - name: Initialize rodsadmin perms
      when: init_rodsadmin_perms | d(false)
      delegate_to: localhost
      become: false
      block:
        - name: Give rodsadmin group write permission on top-level static collections
          irods_permission:
            zone: "{{ _irods_zone_name }}"
            subject: rodsadmin
            permission: write
            object: "{{ item }}"
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
          with_items:
            - /
            - /{{ _irods_zone_name }}
            - /{{ _irods_zone_name }}/home
            - /{{ _irods_zone_name }}/trash
            - /{{ _irods_zone_name }}/trash/home

        - name: Give rodsadmin group own permission on home collections
          irods_permission:
            zone: "{{ _irods_zone_name }}"
            subject: rodsadmin
            permission: own
            object: "{{ item }}"
            recursion: exclusive
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
          with_items:
            - /{{ _irods_zone_name }}/home
            - /{{ _irods_zone_name }}/trash/home

    - name: Ensure anonymous user exists
      delegate_to: localhost
      become: false
      irods_user:
        name: anonymous
        password: ''
        state: present
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: Ensure anonymous user has read access to required collections
      delegate_to: localhost
      become: false
      # no_log: true
      irods_permission:
        subject: anonymous
        permission: read
        object: "{{ item }}"
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"
      with_items:
        - /{{ _irods_zone_name }}
        - /{{ _irods_zone_name }}/home
        - /{{ _irods_zone_name }}/home/shared
        - /{{ _irods_zone_name }}/home/shared/commons_repo/curated

    - name: Start quota usage computation
      delegate_to: localhost
      become: false
      # no_log: true
      ansible.builtin.command:
        cmd: >
          irule --rule-engine-plugin-instance=irods_rule_engine_plugin-irods_rule_language-instance
            cyverse_housekeeping_rescheduleQuotaUsageUpdate null ruleExecOut
        stdin: "{{ _irods_admin_password }}"
      register: results
      changed_when: results.stdout == 'scheduled quota usage updates'

    - name: Start storage free space determination
      delegate_to: localhost
      become: false
      # no_log: true
      ansible.builtin.command:
        cmd: >
          irule --rule-engine-plugin-instance=irods_rule_engine_plugin-irods_rule_language-instance
            cyverse_housekeeping_rescheduleStorageFreeSpaceDetermination null ruleExecOut
        stdin: "{{ _irods_admin_password }}"
      register: results
      changed_when: results.stdout == 'scheduled storage determination'

    - name: Start trash removal
      delegate_to: localhost
      become: false
      # no_log: true
      ansible.builtin.command:
        cmd: >
          irule --rule-engine-plugin-instance=irods_rule_engine_plugin-irods_rule_language-instance
            cyverse_housekeeping_rescheduleTrashRemoval null ruleExecOut
        stdin: "{{ _irods_admin_password }}"
      register: results
      changed_when: results.stdout == 'scheduled trash removal'
  

