---
- name: Restart iRODS service
  hosts: irods
  become: "{{ _irods_become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: Restart
      ansible.builtin.import_tasks: tasks/restart_irods.yml
  tags:
    - non_idempotent
