---
- name: Create coordinating resources
  hosts: irods_catalog
  become: "{{ _irods_become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - name: Create coordinating resource
      irods_resource_hierarchy:
        hierarchy: "{{ item }}"
      with_items: "{{ _irods_resource_hierarchies }}"
