---
# The stop command results are stored in `stop_all_result` for inspection by a
# parent playbook.

- name: Stop all | stop iRODS catalog consumers
  hosts: irods_resource:!irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: Stop
      irods_ctl:
        state: stopped
      register: stop_all_result


- name: Stop all | stop iRODS catalog providers
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: Stop
      irods_ctl:
        state: stopped
      register: stop_all_result
