---
- name: configure AMQP broker
  hosts: rabbitmq
  become: true
  gather_facts: false
  roles:
    - role: cyverse.rabbitmq-vhost
      rabbitmq_vhost_name: "{{ _rabbitmq_vhost }}"
      rabbitmq_vhost_users:
        - name: "{{ _rabbitmq_user }}"
          configure_priv: .*
          write_priv: .*
          read_priv: .*

- include: mk_vaults.yml

- name: Install pika
  hosts: irods
  become: true
  tasks:
    - name: ensure pika installed
      pip:
        name: pika
        state: latest

- include: provision.yml
- include: cfg_irods.yml
