---
- name: create coordinating resources
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - irods_resource_hierarchy:
        hierarchy: "{{ item }}"
      with_items: "{{ _irods_resource_hierarchies }}"
