---
- name: Make storage resources
  ansible.builtin.import_playbook: mk_storage_resources.yml


- name: Configure iRODS for PIRE
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - name: Make PIRE resource hierarchy
      irods_resource_hierarchy:
        hierarchy: "{{ _pire_resource_hierarchy }}"

    - name: Create group for PIRE members
      delegate_to: localhost
      become: false
      irods_group:
        group: pire
        state: present
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: Create public collection
      delegate_to: localhost
      become: false
      irods_collection:
        path: /{{ _irods_zone_name }}/home/shared/eht
        parents: true
        state: present
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: Init PIRE manager
      when: _pire_manager != ''
      delegate_to: localhost
      become: false
      block:
        - name: Add PIRE manager to group
          irods_group_member:
            group: pire
            users:
              - "{{ _pire_manager }}"
            state: present
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"

        - name: Create project collection
          irods_collection:
            path: /{{ _irods_zone_name }}/home/shared/bhpire
            parents: true
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"

        - name: Give PIRE manager own permission on project collection
          irods_permission:
            subject: "{{ _pire_manager }}"
            permission: own
            object: /{{ _irods_zone_name }}/home/shared/bhpire
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"
