---
- name: Make storage resources
  ansible.builtin.import_playbook: irods_storage_resources.yml


- name: Configure iRODS for PIRE
  hosts: irods_catalog
  run_once: true
  tasks:
    - name: Configure iRODS for PIRE
      delegate_to: localhost
      block:
        - name: Make PIRE resource hierarchy
          irods_resource_hierarchy:
            hierarchy: "{{ _pire_resource_hierarchy }}"
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            zone: "{{ _irods_zone_name }}"
            admin_username: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"

        - name: Create group for PIRE members
          irods_group:
            group: pire
            state: present
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"

        - name: Create public collection
          irods_collection:
            path: /{{ _irods_zone_name }}/home/shared/eht
            parents: true
            state: present
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"

        - name: Add PIRE manager to group
          when: _pire_manager != ''
          irods_group_member:
            group: pire
            users:
              - "{{ _pire_manager }}"
            state: present
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"

        - name: Create project collection
          when: _pire_manager != ''
          irods_collection:
            path: /{{ _irods_zone_name }}/home/shared/bhpire
            parents: true
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"

        - name: Give PIRE manager own permission on project collection
          when: _pire_manager != ''
          irods_permission:
            subject: "{{ _pire_manager }}"
            permission: own
            object: /{{ _irods_zone_name }}/home/shared/bhpire
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"
