---
- name: restart iRODS service
  hosts: irods
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  tasks:
    - import_tasks: tasks/restart_irods.yml
  tags:
    - non_idempotent
