---
- name: stop the sftp services
  hosts: sftp
  become: true
  tags:
    - no_testing
  tasks:
    - name: stop sftpgo
      service:
        name: sftpgo
        state: stopped
        enabled: false
