---
- name: start the sftp services
  hosts: sftp
  become: true
  tags:
    - no_testing
  tasks:
    - name: start sftpgo
      service:
        name: sftpgo
        state: started
        enabled: true
        