---
- name: "SPARC'd integration"
  hosts: irods
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: "Remove SPARC'd files"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/irods/sparcd.re
        - /etc/irods/sparcd-env.re
        - /var/lib/irods/msiExecCmd_bin/sparcd-ingest
      notify: Reload iRODS rules

  handlers:
    - name: Reload iRODS rules
