---
- name: Stop all | stop iRODS catalog consumers
  hosts: irods_resource:!irods_catalog
  tasks:
    - name: Stop
      ansible.builtin.import_tasks: tasks/stop_irods.yml


- name: Stop all | stop iRODS catalog providers
  hosts: irods_catalog
  tasks:
    - name: Stop
      ansible.builtin.import_tasks: tasks/stop_irods.yml
