---
- name: Make TerraREF storage resource
  import_playbook: mk_storage_resources.yml


- name: Configure iRODS for TerraREF
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - name: Configure
      when: _terraref_base_collection != ''
      block:
        - name: Create TerraREF resource
          irods_resource_hierarchy:
            hierarchy: "{{ _terraref_resource_hierarchy }}"

        - name: Create project collection
          become: false
          delegate_to: localhost
          irods_collection:
            path: "{{ _terraref_base_collection }}"
            parents: true
            state: present
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"

        - name: Assign owner to project collection
          delegate_to: localhost
          become: false
          irods_permission:
            subject: "{{ _terraref_manager }}"
            permission: own
            object: "{{ _terraref_base_collection }}"
            recursive: true
            host: "{{ groups['irods_catalog'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"
