---
- import_playbook: mk_storage_resources.yml


- name: Configure IES for TerraREF
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - when: _terraref_base_collection != ''
      block:
        - name: create TerraREF resource
          irods_resource_hierarchy:
            hierarchy: "{{ _terraref_resource_hierarchy }}"

        - name: create project collection
          irods_collection:
            path: "{{ _terraref_base_collection }}"
            parents: true

        - name: assign owner to project collection
          irods_permission:
            subject: "{{ _terraref_manager }}"
            permission: own
            object: "{{ _terraref_base_collection }}"
            recursive: true
