---
# This playbook is only valid for prod

- name: Update /etc/hosts
  hosts: irods:!unmanaged_systems
  become: true
  gather_facts: false
  tasks:
    - name: update /etc/hosts
      template:
        src: templates/etc/hosts.j2
        dest: /etc/hosts
