FROM test-env-base:centos7

ARG DB_NAME=ICAT
ARG DB_PASSWORD=testpassword
ARG DB_USER=irods
ARG DBMS_HOST=dbms_configured
ARG DBMS_PORT=5432
ARG DBMS_TYPE=postgres
ARG IRODS_CONTROL_PLANE_KEY=TEMPORARY__32byte_ctrl_plane_key
ARG IRODS_CONTROL_PLANE_PORT=1248
ARG IRODS_DEFAULT_RESOURCE=demoResc
ARG IRODS_FIRST_EPHEMERAL_PORT=20000
ARG IRODS_HOST=csp
ARG IRODS_LAST_EPHEMERAL_PORT=20199
ARG IRODS_NEGOTIATION_KEY=TEMPORARY_32byte_negotiation_key
ARG IRODS_SCHEMA_VALIDATION=https://schemas.irods.org/configuration
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_KEY=TEMPORARY_zone_key
ARG IRODS_ZONE_NAME=tempZone
ARG IRODS_ZONE_PASSWORD=rods
ARG IRODS_ZONE_PORT=1247
ARG IRODS_ZONE_USER=rods

ADD https://packages.irods.org/renci-irods.yum.repo /etc/yum.repos.d/renci-irods.yum.repo

COPY irods-provider/config/pre_config.re /etc/irods/

RUN \
	--mount=target=/tmp/config-irods,source=irods-provider/scripts/config-irods.sh \
	--mount=target=/tmp/service.sh.template,source=irods-provider/scripts/service.sh.template \
	--mount=target=/tmp/prep-svc-script,source=irods-provider/scripts/prep-svc-script.sh \
<<EOF
	set -o errexit

### Install PostgreSQL ODBC connector
	yum --assumeyes install \
		https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
	yum --assumeyes install postgresql12-odbc

### Install iRODS
	rpm --import https://packages.irods.org/irods-signing-key.asc
	yum --assumeyes versionlock add \
		irods-database-plugin-postgres-4.2.8 \
		irods-icommands-4.2.8 \
		irods-runtime-4.2.8 \
		irods-server-4.2.8
# XXX - python3-pyodbc required by irods-server but not available as system package in CentOS 7
	yum --assumeyes install gcc gcc-c++ unixODBC-devel
	pip3 install pyodbc
	yum --assumeyes erase gcc gcc-c++ unixODBC-devel
# XXX - ^^^
# XXX - irods-icommands required by irods-server but not installed by dependency resolution in
#       CentOS 7, 4.3.1
	yum --assumeyes install irods-icommands
# XXX - ^^^
	yum --assumeyes install irods-server irods-database-plugin-postgres

### Install libraries required by command scripts
	pip3 install pika==1.1

### Configure ODBC and iRODS
/tmp/config-irods

### Create service script
	/tmp/prep-svc-script

### Install testing support artifacts
	pip3 --quiet install python-irodsclient

### Clean yum cache
	yum clean all
	rm --force --recursive /var/cache/yum
EOF

CMD [ "/service.sh" ]
