FROM test-env-base:ubuntu1804

ARG DBMS_HOST=dbms_configured
ARG DBMS_PORT=5432
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_PASSWORD=rods

### Create service script
RUN \
	--mount=target=/tmp/service.sh.template,source=irods-consumer/scripts/service.sh.template \
	--mount=target=/tmp/prep-svc-script,source=irods-consumer/scripts/prep-svc-script.sh \
	/tmp/prep-svc-script

CMD [ "/service.sh" ]
