#! /bin/bash
#
# This script builds the ansible-tester image.


if [[ "$OSTYPE" == "darwin"* ]]
then
  readonly ExecName=$(greadlink -f "$0")
else
  readonly ExecName=$(readlink --canonicalize "$0")
fi

main()
{
  local baseDir=$(dirname "$ExecName")

  docker build --tag ansible-tester "$baseDir"
}


set -e

main
