#!/usr/bin/env bash
#
# This script builds the ansible-tester image.

set -o errexit -o nounset -o pipefail

EXEC_NAME=$(readlink --canonicalize "$0")
readonly EXEC_NAME

declare BaseDir


main()
{
  BaseDir="$(dirname "$EXEC_NAME")"

  local cfg="$1"

  if [[ -z "$cfg" ]]; then
    printf 'An environment variable include file is needed.\n' >&2
    return 1
  fi

  if ! [[ "$cfg" =~ ^/ ]]; then
    cfg="$(pwd)"/"$cfg"
  fi

  # shellcheck disable=SC1090
  . "$cfg"

  cp --no-clobber "$BaseDir"/../../requirements-ansible.yml "$BaseDir"/requirements.yml
  trap 'rm --force "$BaseDir"/requirements.yml' EXIT

  local buildArgs=(
#    --no-cache
    --build-arg=IRODS_CLERVER_PASSWORD="$IRODS_CLERVER_PASSWORD"
    --tag=ansible-tester )

  docker buildx build "${buildArgs[@]}" "$BaseDir"
}


main "$@"
