#! /bin/bash
#
# This script deletes the ansible-tester image.


main()
{
  if [ -n "$(docker images --filter reference=ansible-tester | tail --lines +2)" ]
  then
    docker rmi ansible-tester
  fi
}


main
