#!/bin/bash
#
# Usage:
#  run INSPECT PRETTY PLAYBOOKS PLAYBOOK INVENTORY
#
# Parameters:
#  INSPECT    if this is `true`, a shell will be opened that allows access to
#             the volumes in the env containers.
#  PRETTY     if this is `true`, more info is dumped and newlines in ouput are
#             expanded.
#  PLAYBOOKS  the base directory for the set of playbooks containing PLAYBOOK.
#  PLAYBOOK   the name of the playbook being tested.
#  HOSTS      the inventory hosts to test against
#
# Envinroment Variables:
#  DBMS_HOST                 The hostname of the PostgreSQL server to connect to
#  ENV_NAME                  The docker environment to join
#  IRODS_PROVIDER_CONF_HOST  The host name of the iRODS catalog service provider 
#                            to connect to
#  IRODS_ZONE_NAME           The name of the iRODS zone inside the testing
#                            environment

set -o errexit


main()
{
  local doInspect="$1"
  local pretty="$2"
  local playbooks="$3"
  local playbook="$4"
  local hosts="$5"

  docker run --interactive --rm --tty \
             --env IRODS_HOST="$IRODS_PROVIDER_CONF_HOST" \
             --env IRODS_ZONE_NAME="$IRODS_ZONE_NAME" \
             --env PGHOST="$DBMS_HOST" \
             --network "$DOMAIN" \
             --volume "$playbooks":/playbooks-under-test:ro \
             ansible-tester "$doInspect" "$pretty" "$playbook" "$hosts" ''
}


main "$@"
