#!/bin/bash
#
# Usage:
#  run INSPECT PRETTY VERBOSE PLAYBOOKS INVENTORY [PLAYBOOK]
#
# Parameters:
#  HOSTS      the inventory hosts to test against
#  INSPECT    if this is `true`, a shell will be opened that allows access to
#             the volumes in the env containers.
#  PLAYBOOK   the name of the playbook being tested.
#  PLAYBOOKS  the base directory for the set of playbooks containing PLAYBOOK.
#  PRETTY     if this is `true`, more info is dumped and newlines in ouput are
#             expanded.
#  VERBOSE    if this is `true`, -vvv verbose output is generated
#
# Envinroment Variables:
#  DBMS_HOST                 The hostname of the PostgreSQL server to connect to
#  ENV_NAME                  The docker environment to join
#  IRODS_PROVIDER_CONF_HOST  The host name of the iRODS catalog service provider 
#                            to connect to
#  IRODS_ZONE_NAME           The name of the iRODS zone inside the testing
#                            environment

set -o errexit -o nounset -o pipefail


main() {
	local doInspect="$1"
	local pretty="$2"
  local verbose="$3"
	local playbooks="$4"
	local hosts="$5"

	local playbook
	if (( $# >= 6 ))
	then
		playbook="$6"
	fi

	docker run --interactive --rm --tty \
		--env IRODS_HOST="$IRODS_PROVIDER_CONF_HOST" \
		--env IRODS_ZONE_NAME="$IRODS_ZONE_NAME" \
		--env PGHOST="$DBMS_HOST" \
		--network "$DOMAIN" \
		--volume "$playbooks":/playbooks-under-test:ro \
		ansible-tester "$doInspect" "$hosts" "${playbook-}" "$pretty" "$verbose"
}


main "$@"
