---
# This playbook waits for all of the systems under test to become ready.

- name: Wait for testing systems
  hosts: all:!localhost
  gather_facts: false
  tasks:
    - name: Wait for testing system to become reachable
      ansible.builtin.wait_for_connection:
        delay: 1
        connect_timeout: 10
        timeout: 30
