---
# This playbook waits for all of the systems under test to become ready.

- name: wait for testing systems
  hosts: all:!localhost
  gather_facts: false
  tasks:
    - name: wait for testing system to become reachable
      wait_for_connection:
        timeout: 30
