---
# restart_op  the type of restart to perform, either `always` or `if running`
- name: Restart iRODS | determine is iRODS configured
  when: restart_op != 'always'
  ansible.builtin.stat:
    path: /etc/irods/server_config.json
  register: resp

- name: Restart iRODS | restart
  when: restart_op == 'always' or resp.stat.exists
  block:
    - name: Stop catalog service consumers
      when: inventory_hostname in groups['irods_resource'] | difference(groups['irods_catalog'])
      become: "{{ _become_svc_acnt }}"
      become_user: "{{ _irods_service_account_name }}"
      irods_ctl:
        state: stopped
      register: stop_resp

    - name: Restart catalog service providers
      when: inventory_hostname in groups['irods_catalog']
      become: "{{ _become_svc_acnt }}"
      become_user: "{{ _irods_service_account_name }}"
      irods_ctl:
        state: "{{ 'restarted' if restart_op == 'always' else 'restarted_if_running' }}"

    - name: Start catalog service consumers
      when: >-
        inventory_hostname in groups['irods_resource'] | difference(groups['irods_catalog'])
        and (stop_resp is changed or restart_op == 'always')
      become: "{{ _become_svc_acnt }}"
      become_user: "{{ _irods_service_account_name }}"
      irods_ctl:
        state: started
