---
- name: Restart iRODS | stop catalog consumers
  when: inventory_hostname in groups['irods_resource'] | difference(groups['irods_catalog'])
  ansible.builtin.include_tasks: stop_irods.yml

- name: Restart iRODS | restart catalog providers
  when: inventory_hostname in groups['irods_catalog']
  irods_ctl:
    state: restarted

- name: Restart iRODS | start catalog consumers
  when: inventory_hostname in groups['irods_resource'] | difference(groups['irods_catalog'])
  irods_ctl:
