---
- name: Install sftpgo | binary
  ansible.builtin.copy:
    src: /tmp/sftpgo_setup/sftpgo
    dest: /usr/bin/sftpgo
    owner: root
    group: root
    mode: '0755'
    remote_src: true

- name: Install sftpgo | Remove old template, openapi, static files
  ansible.builtin.file:
    path: /usr/share/sftpgo
    state: absent

- name: Install sftpgo | template, openapi, static files
  ansible.builtin.copy:
    src: /tmp/sftpgo_setup/usr/share/sftpgo
    dest: /usr/share
    owner: root
    group: root
    mode: '0755'
    remote_src: true
