#! /bin/bash


main()
{
  local baseDir=$(dirname $(readlink -f "$0"))
  local cfg="$@"

  if [ -z "$cfg" ]
  then
    printf 'An environment variable include file is needed.\n' >&2
    return 1
  fi

  if ! [[ "$cfg" =~ ^/ ]]
  then
    cfg="$(pwd)"/"$cfg"
  fi

  . "$cfg"

  docker-compose --file "$baseDir"/docker-compose.yml --project-name "$ENV_NAME" build
}


set -e

main "$*"
