#! /bin/bash
#
# Usage:
#  build INC_FILE
#
# PARAMETERS:
#  INC_FILE  The absolute path to a file including the build time environment
#            variables. See README.md for details.
#
# Builds the five docker images with the provided configuration values.


main()
{
  local baseDir=$(dirname $(readlink -f "$0"))
  local cfg="$@"

  if [ -z "$cfg" ]
  then
    printf 'An environment variable include file is needed.\n' >&2
    return 1
  fi

  if ! [[ "$cfg" =~ ^/ ]]
  then
    cfg="$(pwd)"/"$cfg"
  fi

  . "$cfg"

  docker build --file "$baseDir"/base/Dockerfile.centos6 --tag test-env-base:centos6 "$baseDir"
  docker build --file "$baseDir"/base/Dockerfile.centos7 --tag test-env-base:centos7 "$baseDir"
  docker-compose --file "$baseDir"/docker-compose.yml --project-name "$ENV_NAME" build
}


set -e

main "$*"
