#! /bin/bash


main()
{
  local baseDir=$(dirname $(readlink -f "$0"))

  while read -r repository rest
  do
    docker rmi "$repository"
  done < <(docker images --filter reference="$ENV_NAME"_* | tail --lines +2)
}


main
