#! /bin/bash
#
# Usage:
#  clean INC_FILE
#
# PARAMETERS:
#  INC_FILE  The absolute path to a file including the build time environment
#            variables.
#
# Deletes the four docker images.
#
# Here are the environment variables that must be exported from INC_FILE.
#
# DBMS_HOST                   The FQDN or IP address of the PostgreSQL server
# ENV_NAME                    The docker-compose project name.
# IRODS_DEFAULT_RESOURCE      The name of the default resource to use
# IRODS_IES                   The FQDN or IP address of the IES.
# IRODS_LAST_EPHEMERAL_PORT   The end of the port range available for parallel
#                             transfer and reconnections.
# IRODS_RS6_HOST              The FQDN or IP address of the server hosting the
#                             CentOS 6 resource server
# IRODS_RS6_NAME              The name of the resource hosted by IRODS_RS6_HOST
# IRODS_RS7_HOST              The FQDN or IP address of the server hosting the
#                             CentOS 7 resource server
# IRODS_RS7_NAME              The name of the resource hosted by IRODS_RS7_HOST
# IRODS_SCHEMA_VALIDATION     The URI for the schema used to validate the
#                             configuration files or 'off'.
# IRODS_VAULT                 The absolute path to the vault on the resource
#                             servers
# IRODS_ZONE_NAME             The name of the iRODS zone


main()
{
  local baseDir=$(dirname $(readlink -f "$0"))
  local cfg="$@"

  if [ -z "$cfg" ]
  then
    printf 'An environment variable include file is needed.\n' >&2
    return 1
  fi

  if ! [[ "$cfg" =~ ^/ ]]
  then
    cfg="$(pwd)"/"$cfg"
  fi

  . "$cfg"

  while read -r repository rest
  do
    docker rmi "$repository"
  done < <(docker images --filter reference="$ENV_NAME"_* | tail --lines +2)
}


main "$*"
