#! /bin/bash
#
# Usage:
#  controller INC_FILE (start|stop)
#
# PARAMETERS:
#  INC_FILE  The absolute path to a file including the build time environment
#            variables. See README.md for details.
#
# Starts or stops all of the containers.

set -e


if [[ "$OSTYPE" == "darwin"* ]]
then
  readonly ExecName=$(greadlink -f "$0")
else
  readonly ExecName=$(readlink --canonicalize "$0")
fi

main()
{
  local baseDir=$(dirname "$ExecName")

  if [ "$#" -lt 1 ]
  then
    printf 'An environment variable include file is required as its first parameter.\n' >&2
    return 1
  fi

  local cfg="$1"

  if [ "$#" -lt 2 ]
  then
    printf 'Requires either "start" or "stop" as its second parameter.\n' >&2
    return 1
  fi

  local action="$2"

  if ! [[ "$cfg" =~ ^/ ]]
  then
    cfg="$(pwd)"/"$cfg"
  fi

  . "$cfg"

  case "$action" in
    start)
      local dcCmd='up -d --scale dbms_unconfigured=2'
      ;;
    stop)
      local dcCmd='down --remove-orphans --volumes'
      ;;
    *)
      printf 'Unknown command "%s"\n' "$action" >&2
      return 1
      ;;
  esac

  docker-compose --file "$baseDir"/docker-compose.yml --project-name "$ENV_NAME" $dcCmd
}


main "$@"
