#! /bin/bash
#
# Usage:
#  inspect INC_FILE
#
# PARAMETERS:
#  INC_FILE  The absolute path to a file including the build time environment
#            variables. See README.md for details.
#
# Opens a container that allows inspection of the volumes in the environment.


main()
{
  local baseDir=$(dirname $(readlink -f "$0"))
  local cfg="$@"

  if [ -z "$cfg" ]
  then
    printf 'An environment variable include file is needed.\n' >&2
    return 1
  fi

  if ! [[ "$cfg" =~ ^/ ]]
  then
    cfg="$(pwd)"/"$cfg"
  fi

  . "$cfg"

  docker-compose --file "$baseDir"/docker-compose.yml --project-name "$ENV_NAME" \
                 exec volume_inspector /bin/bash
}


set -e

main "$*"
